ALTER TABLE USER
DROP display_flag,
ADD  city varchar(100) DEFAULT NULL,
ADD  title varchar(100) DEFAULT NULL,
ADD  introduction varchar(1000) DEFAULT NULL,
MODIFY COLUMN github varchar(100) DEFAULT NULL,
ADD  linkedin varchar(100) DEFAULT NULL,
ADD  personalwebsite varchar(100) DEFAULT NULL,
ADD  resume varchar(100) DEFAULT NULL,
ADD  title1 varchar(100) DEFAULT NULL,
ADD  title2 varchar(100) DEFAULT NULL,
ADD  title3 varchar(100) DEFAULT NULL,
ADD  title4 varchar(100) DEFAULT NULL,
ADD  title5 varchar(100) DEFAULT NULL,
ADD  skill1 varchar(100) DEFAULT NULL,
ADD  skill2 varchar(100) DEFAULT NULL,
ADD  skill3 varchar(100) DEFAULT NULL,
ADD  skill4 varchar(100) DEFAULT NULL,
ADD  skill5 varchar(100) DEFAULT NULL,
ADD  skill6 varchar(100) DEFAULT NULL,
ADD  skill7 varchar(100) DEFAULT NULL,
ADD  skill8 varchar(100) DEFAULT NULL,
ADD  skill9 varchar(100) DEFAULT NULL,
ADD  skill10 varchar(100) DEFAULT NULL,
ADD  publish_flag char(1) DEFAULT 'N',
ADD  notify_flag char(1) DEFAULT 'N',
  MODIFY COLUMN role char(1) DEFAULT 'V',
  MODIFY COLUMN status char(1) DEFAULT 'A'