Update USER SET 
 city = "testCity",
 title = "testtitle",
 introduction = "testinto",
 linkedin ="testlinkedin",
 personalwebsite ="testWebsite",
 resume ="testResume",
 title1 = "testTitle1",
 title2 = "testTitle2",
 title3 = "testTitle3",
 title4 = "testTitle4", 
 title5 = "testTitle5",
 skill1 = "testSkill1",
 skill2 = "testSkill2",
 skill3 = "testSkill3",
 skill4 = "testSkill4",
 skill5 = "testSkill5",
 skill6 = "testSkill6",
 skill7 = "testSkill7",
 skill8 = "testSkill8",
 skill9 = "testSkill9",
 skill10 = "testSkill10"
WHERE id BETWEEN 2 AND 6;


Update USER SET 
 city = "testCity",
 title = "testtitle",
 introduction = "testinto",
 linkedin ="testlinkedin",
 personalwebsite ="testWebsite",
 resume ="testResume",
 title1 = "testTitle1",
 title2 = "testTitle2",
 title3 = "testTitle3",
 title4 = "testTitle4", 
 title5 = "testTitle5",
 skill1 = "testSkill1",
 skill2 = "testSkill2",
 skill3 = "testSkill3",
 skill4 = "testSkill4",
 skill5 = "testSkill5",
 skill6 = "testSkill6",
 skill7 = "testSkill7",
 skill8 = "skill8",
 skill9 = "skill9",
 skill10 = "skillten",
 publish_flag = "Y",
 notify_flag = "Y",
 status = "A",
 role = "D"
WHERE id = 7;